version: '3.8'

services:
  db:
    image: mysql:8
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_DATABASE: releases_db  
      MYSQL_USER: app_user 
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_password
    ports:
      - "3306:3306"  
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d  
    secrets:
      - mysql_root_password
      - mysql_password
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    build: .
    container_name: node_app
    environment:
      DB_HOST: db  
      DB_USER: app_user  
      DB_PASSWORD_FILE: /run/secrets/mysql_password 
      DB_DATABASE: releases_db  
      DB_PORT: 3306  
      API_KEY: ${API_KEY}  
    ports:
      - "3000:3000"  
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    secrets:
      - mysql_password
    command: ["./wait-for-it.sh", "db:3306", "--", "npm", "start"]
    restart: unless-stopped

networks:
  app-network:  
    driver: bridge

secrets:
  mysql_root_password:
    file: ./secrets/mysql_root_password.txt  
  mysql_password:
    file: ./secrets/mysql_password.txt  
